"""Add Google refresh token and expiry fields

Revision ID: 25d07fefcf3b
Revises: 4be4ddb3a267
Create Date: 2025-04-11 13:24:24.300801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d07fefcf3b'
down_revision = '4be4ddb3a267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_refresh_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('google_refresh_token')

    # ### end Alembic commands ###
