"""empty message

Revision ID: 4be4ddb3a267
Revises: 99a187322ba1
Create Date: 2025-04-08 20:06:52.374756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be4ddb3a267'
down_revision = '99a187322ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('main_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('uq_entries_main_text', type_='unique')
        batch_op.drop_constraint('uq_entries_title', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_entries_title', ['title'])
        batch_op.create_unique_constraint('uq_entries_main_text', ['main_text'])
        batch_op.alter_column('main_text',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
