"""added google token

Revision ID: 62025edf3eb7
Revises: ae6070e4193f
Create Date: 2025-04-03 14:37:48.414244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62025edf3eb7'
down_revision = 'ae6070e4193f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_token')

    # ### end Alembic commands ###
