"""del user model upgrade cascade

Revision ID: 6a90ed79584b
Revises: 25d07fefcf3b
Create Date: 2025-04-13 14:19:58.792403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a90ed79584b'
down_revision = '25d07fefcf3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_moods', schema=None) as batch_op:
        batch_op.drop_constraint('fk_entry_moods_entry_id_entries', type_='foreignkey')
        batch_op.drop_constraint('fk_entry_moods_mood_id_moods', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_entry_moods_mood_id_moods'), 'moods', ['mood_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_entry_moods_entry_id_entries'), 'entries', ['entry_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_moods', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_entry_moods_entry_id_entries'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_entry_moods_mood_id_moods'), type_='foreignkey')
        batch_op.create_foreign_key('fk_entry_moods_mood_id_moods', 'moods', ['mood_id'], ['id'])
        batch_op.create_foreign_key('fk_entry_moods_entry_id_entries', 'entries', ['entry_id'], ['id'])

    # ### end Alembic commands ###
