"""Nullable color = True so default color can work

Revision ID: 99a187322ba1
Revises: 62025edf3eb7
Create Date: 2025-04-03 16:40:35.417516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a187322ba1'
down_revision = '62025edf3eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)

    # ### end Alembic commands ###
